name: "dbt Cloud Column Aware CI"
description: "This action will run dbt Cloud CI jobs taking into account downstream dependencies from projects set up with dbt Mesh"
branding:
  icon: "cloud"
  color: "orange"
author: "Doug Guthrie"
inputs:
  dbt_cloud_service_token:
    description: dbt Cloud Service Token
    required: true
  dbt_cloud_token_value:
    description: dbt Cloud Personal API Key for use with the dbt Cloud CLI
    required: true
  dbt_cloud_token_name:
    description: The name of the personal API Key created in dbt Cloud
    required: true
  dbt_cloud_account_id:
    description: dbt Cloud Account ID
    required: true
  dbt_cloud_project_id:
    description: dbt Cloud Project ID
    required: true
  dbt_cloud_project_name:
    description: dbt Cloud Project Name
    required: true
  dbt_cloud_job_id:
    description: dbt Cloud CI Job ID for the current project
    required: true
  dbt_cloud_host:
    description: dbt Cloud host
    required: false
    default: "cloud.getdbt.com"
  dbt_cloud_environment_id:
    description: dbt Cloud Environment ID (this is the environment that the CI job defers to).  If not given, it will be inferred from the CI job.
    required: false
  log_level:
    description: "Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)"
    required: false
    default: "INFO"
  dialect:
    description: "SQL dialect used in the dbt project (e.g., 'snowflake', 'bigquery', 'redshift')"
    required: true
  dry_run:
    description: "If true, will compile and analyze changes but won't trigger the dbt Cloud job"
    required: false
    default: false
  github_token:
    description: "GitHub token for API authentication"
    required: true
    default: ${{ github.token }}
runs:
  using: "docker"
  image: "Dockerfile"
